"""link and media models and schemas update based on extracted data

Revision ID: 005ca2668c2b
Revises: 4c89fabcf151
Create Date: 2026-06-14 22:06:54.722639

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "005ca2668c2b"
down_revision: Union[str, Sequence[str], None] = "4c89fabcf151"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Create enum types first
    linklanguage = sa.Enum("softsub", "dubbed", "hardcoded", name="linklanguage")
    linklanguage.create(op.get_bind())

    mediatypes = sa.Enum("series", "movie", name="mediatypes")
    mediatypes.create(op.get_bind())
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("links", sa.Column("quality", sa.String(length=20), nullable=True))
    op.add_column("links", sa.Column("codec", sa.String(length=100), nullable=True))
    op.add_column(
        "links",
        sa.Column(
            "language",
            sa.Enum("softsub", "dubbed", "hardcoded", name="linklanguage"),
            nullable=True,
        ),
    )
    op.add_column("links", sa.Column("size", sa.String(length=50), nullable=True))
    op.add_column("media", sa.Column("imdb_id", sa.String(length=20), nullable=True))
    op.add_column("media", sa.Column("tmdb_id", sa.Integer(), nullable=True))
    op.add_column("media", sa.Column("imdb_rate", sa.Float(), nullable=True))
    op.add_column("media", sa.Column("tmdb_rate", sa.Float(), nullable=True))
    op.add_column("media", sa.Column("imdb_votes", sa.Integer(), nullable=True))
    op.add_column("media", sa.Column("tmdb_votes", sa.Integer(), nullable=True))
    op.add_column("media", sa.Column("popularity", sa.Float(), nullable=True))
    op.add_column("media", sa.Column("overview", sa.Text(), nullable=True))
    op.add_column("media", sa.Column("tagline", sa.String(length=500), nullable=True))
    op.add_column("media", sa.Column("genres", sa.String(length=300), nullable=True))
    op.add_column("media", sa.Column("poster", sa.String(length=500), nullable=True))
    op.add_column("media", sa.Column("backdrop", sa.String(length=500), nullable=True))
    op.add_column("media", sa.Column("total_seasons", sa.Integer(), nullable=True))
    op.add_column("media", sa.Column("total_episodes", sa.Integer(), nullable=True))
    op.execute(
        "ALTER TABLE media ALTER COLUMN type TYPE mediatypes USING type::text::mediatypes"
    )
    op.execute("DROP TYPE IF EXISTS mediatype")
    op.alter_column(
        "media", "country", existing_type=sa.VARCHAR(length=100), nullable=True
    )
    op.create_unique_constraint(None, "media", ["tmdb_id"])
    op.create_unique_constraint(None, "media", ["imdb_id"])
    op.drop_column("media", "detail")
    op.drop_column("media", "rate")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "media",
        sa.Column(
            "rate",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "media",
        sa.Column(
            "detail", sa.VARCHAR(length=1000), autoincrement=False, nullable=True
        ),
    )
    op.drop_constraint(None, "media", type_="unique")
    op.drop_constraint(None, "media", type_="unique")
    op.alter_column(
        "media", "country", existing_type=sa.VARCHAR(length=100), nullable=False
    )
    op.execute(
        "ALTER TABLE media ALTER COLUMN type TYPE mediatypes USING type::text::mediatypes"
    )
    op.execute("DROP TYPE IF EXISTS mediatype")
    op.drop_column("media", "total_episodes")
    op.drop_column("media", "total_seasons")
    op.drop_column("media", "backdrop")
    op.drop_column("media", "poster")
    op.drop_column("media", "genres")
    op.drop_column("media", "tagline")
    op.drop_column("media", "overview")
    op.drop_column("media", "popularity")
    op.drop_column("media", "tmdb_votes")
    op.drop_column("media", "imdb_votes")
    op.drop_column("media", "tmdb_rate")
    op.drop_column("media", "imdb_rate")
    op.drop_column("media", "tmdb_id")
    op.drop_column("media", "imdb_id")
    op.drop_column("links", "size")
    op.drop_column("links", "language")
    op.drop_column("links", "codec")
    op.drop_column("links", "quality")
    # ... drop columns first ...

    # drop enum types last
    sa.Enum(name="linklanguage").drop(op.get_bind())
    sa.Enum(name="mediatypes").drop(op.get_bind())
    # ### end Alembic commands ###
