"""type enum in media model fixed

Revision ID: 08b2a9ab0806
Revises: 9e0a7d09893a
Create Date: 2026-05-31 23:29:55.751857

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08b2a9ab0806'
down_revision: Union[str, Sequence[str], None] = '9e0a7d09893a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
