"""episodes col removed from Link table

Revision ID: 4c89fabcf151
Revises: 686d3cd9d837
Create Date: 2026-06-14 01:34:00.057004

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c89fabcf151'
down_revision: Union[str, Sequence[str], None] = '686d3cd9d837'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('links', 'episode')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('links', sa.Column('episode', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
