"""profile updated

Revision ID: 9e0a7d09893a
Revises: d0d7acd1a942
Create Date: 2026-05-31 15:17:44.240430

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e0a7d09893a'
down_revision: Union[str, Sequence[str], None] = 'd0d7acd1a942'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('profiles', 'fullname',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('profiles', 'email',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.alter_column('profiles', 'sex',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('profiles', 'sex',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('profiles', 'email',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.alter_column('profiles', 'fullname',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    # ### end Alembic commands ###
