"""duration can be null now

Revision ID: d64702b2aa73
Revises: 005ca2668c2b
Create Date: 2026-06-14 22:27:18.986881

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd64702b2aa73'
down_revision: Union[str, Sequence[str], None] = '005ca2668c2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('media', 'duration',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('media', 'duration',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
